### PR TITLE
Outdated certificate has been updated

### PR DESCRIPTION
**Pull request by imflop**
Updated the certificate to 2050

```
$ openssl x509 -enddate -noout -in pytest_hoverfly/cert.pem
notAfter=Mar 18 10:03:03 2050 GMT
```

### CODE REVIEW

**Review by Se7ge — APPROVED** [review]
Please fix tests

**Comment by imflop** [comment]
> Please fix tests

@Se7ge Tests cannot be fixed right now.

Application depends on the [public image](https://github.com/wrike/pytest-hoverfly/blob/master/pytest_hoverfly/base.py#L18) where the expired keys are [stored](https://github.com/SpectoLabs/hoverfly/blob/master/core/cert.pem).

I suggest two ways to solve the problems:

1. Wait for the developers to fix the [issue](https://github.com/SpectoLabs/hoverfly/issues/1011) and update the [images](https://hub.docker.com/r/spectolabs/hoverfly)
2. Use own version of hoverfly with certificates which expiration date has been set by us.

**Comment by Se7ge** [comment]
> Wait for the developers to fix the https://github.com/SpectoLabs/hoverfly/issues/1011 and update the [images](https://hub.docker.com/r/spectolabs/hoverfly)

@imflop looks like it didn't help, do you know the reason?

@WouldYouKindly would you like to check it?

**Comment by Se7ge** [comment]
@imflop also version should be bumped and changelog should be updated

**Pull request merged**
